### ISSUE TITLE
Revisiting Resource Allocation Logic

### ISSUE THREAD

**Issue by Bergam0t** [RichardPilbery/DAA_DES#238]
Having spent some time playing with this, I've reached the point where I need to step back, map this out by hand, and revisit afresh. 

I think we effectively now have two separate functions where the resources currently in the store are iterated through, and the most ideal resource given what's available is returned.
- what's ideal is sometimes based on some pre-rolled attributes of the patients, using historical data 

This also ties in with what the CC/EC/Reg/Reg with Helicopter Benefit care categories are intended to be. 

- Are they a way for us to create some predictions of instances where patient benefit has been missed or increased by changes to the operational model?
- Or are they ways for us to capture some of the nuance in the dispatcher's decisions of what's sent
-  (or a combination of the above)

And are preferred callsign groups meant to reflect 
- the preference for the CC/EC equipped resources
- or the element of geography we're otherwise unable to capture (i.e. some jobs are best for H71 and CC72 due to their location)

**Comment by Bergam0t** [comment]
Quick summary of my understanding of what currently happens. 

I've been fiddling with it this week trying to get it closer to reality in terms of figs, but I'm not sure that means the logic is fully consistent anymore. 

Though in terms of figs
- missed jobs look good
- callsign group 71 is getting tasked too often (worse in busier periods I think)
- car/heli split in csg 70 is good
- car/heli split in csg 71 less good
- H70 utilisation a little low
- H71 utilisation a little high
- car utilisation in right ballpark (a little low for CC72, backup cars better)

Kicks off in des_hems with

```
            if pt.hems_cc_or_ec == 'REG':
                # Separate (basically the old way of doing things)
                # function to determine HEMS resource based on callsign group, vehicle type and yearly quarter
                hems_res_list: list[HEMS|None, str, HEMS|None] = yield self.hems_resources.allocate_regular_resource(pt)
            else:
                hems_res_list: list[HEMS|None, str, HEMS|None] = yield self.hems_resources.allocate_resource(pt)
```

## Regular jobs 

This uses the function `preferred_regular_group_available`

Ignoring any resources that are in use, being serviced, not on shift, are part of a callsign group that's already occupied:

- if it's predicted to be a heli benefit case (but no cc or ec benefit predicted)
    - prefers the cc heli
    -  will send the ec heli if that's not available
    - will say there's no resource available if neither heli is available
    (see #234 for my ponderings on this)

- if it's not predicted to be a heli benefit case (and no cc or ec benefit predicted either)
    - uses the 'preferred group' and 'preferred vehicle type' attributes of the patient
    - then would prefer any helicopter
    - then would prefer anything else from it's preferred callsign group
    - then would just send anything it can get 


## CC/EC jobs

This uses the function `preferred_resource_available`

Ignoring any resources that are in use, being serviced, not on shift, are part of a callsign group that's already occupied:

- tries to send the best helicopter for the care category (i.e. tries to send a CC resource to a predicted CC job)
- then would prefer the right care category but the wrong vehicle (i.e. would prefer sending CC70 to a CC job over an EC heli)
- then tries for heli of the wrong care category
- then tries for car of the wrong care category
