### ISSUE TITLE
Explore how to make call handling logic manageable through config files and/or the frontend

### ISSUE THREAD

**Issue by Bergam0t** [RichardPilbery/DAA_DES#257]
Fundamentally resource allocation logic is built up in a series of checks like this against the resource object (with a series of defined attributes) and the patient object (with its own series of defined attributes). It then refers back to a series of possible match codes to return useful information about the match that occurred.

```python
# 1. Best case: resource category matches preferred care category *and* is a helicopter
if h.category == pt.preferred_category and h.vehicle_type == "helicopter":
    priority = 1
    lookup = ResourceAllocationReason.MATCH_PREFERRED_CARE_CAT_HELI

# 2. Next best: resource category matches preferred care category, but is a car
elif h.category == pt.preferred_category:
    priority = 2
    lookup = ResourceAllocationReason.MATCH_PREFERRED_CARE_CAT_CAR

# 3–4. Category mismatch fallback options:
# For a CC preference, fall back to EC providers if needed
elif preferred_category == "CC":
    if h.category == "EC" and h.vehicle_type == "helicopter":
        priority = 3
        lookup = ResourceAllocationReason.CC_MATCH_EC_HELI
    elif h.category == "EC":
        priority = 4
        lookup = ResourceAllocationReason.CC_MATCH_EC_CAR

# For an EC preference, fall back to CC providers if needed
elif preferred_category == "EC":
    if h.category == "CC" and h.vehicle_type == "helicopter":
        priority = 3
        lookup = ResourceAllocationReason.EC_MATCH_CC_HELI
    elif h.category == "CC":
        priority = 4
        lookup = ResourceAllocationReason.EC_MATCH_CC_CAR

```

There are currently separate functions for patients who are EC/CC, and those who are regular. Within the regular patients function, there is also a separate path for those who are heli benefit. There is a separate check done to simulate how much a call handler will know about the resource to be sent in advance (i.e. how likely they are to follow the CC/EC path, and how likely they are to go ahead and send a car to a heli benefit job. 

To facilitate changing the impact of testing different dispatching criteria, and also to allow different air ambulances to easily define their own dispatching criteria, I wonder if it's possible to move this logic out into its own config files.

e.g. a YAML file like this:

```yaml
matching_rules:
  - condition:
      preferred_category: "{resource.category}"
      vehicle_type: "helicopter"
    priority: 1
    reason: MATCH_PREFERRED_CARE_CAT_HELI

  - condition:
      preferred_category: "{resource.category}"
    priority: 2
    reason: MATCH_PREFERRED_CARE_CAT_CAR

  # CC preference fallback
  - condition:
      preferred_category: "CC"
      resource_category: "EC"
      vehicle_type: "helicopter"
    priority: 3
    reason: CC_MATCH_EC_HELI

  - condition:
      preferred_category: "CC"
      resource_category: "EC"
    priority: 4
    reason: CC_MATCH_EC_CAR

  # EC preference fallback
  - condition:
      preferred_category: "EC"
      resource_category: "CC"
      vehicle_type: "helicopter"
    priority: 3
    reason: EC_MATCH_CC_HELI

  - condition:
      preferred_category: "EC"
      resource_category: "CC"
    priority: 4
    reason: EC_MATCH_CC_CAR

```

Or more general, along the lines of 

```yaml
matching_rules:
  - if:
      patient.preferred_category: resource.category
      resource.vehicle_type: helicopter
    then:
      priority: 1
      reason: MATCH_PREFERRED_CARE_CAT_HELI
    stop_if_matched: true

  - if:
      patient.preferred_category: resource.category
    then:
      priority: 2
      reason: MATCH_PREFERRED_CARE_CAT_CAR

  - if:
      patient.preferred_category: CC
      resource.category: EC
      resource.vehicle_type: helicopter
    then:
      priority: 3
      reason: CC_MATCH_EC_HELI

  - if:
      patient.preferred_category: CC
      resource.category: EC
    then:
      priority: 4
      reason: CC_MATCH_EC_CAR

  - if:
      patient.preferred_category: EC
      resource.category: CC
      resource.vehicle_type: helicopter
    then:
      priority: 3
      reason: EC_MATCH_CC_HELI

  - if:
      patient.preferred_category: EC
      resource.category: CC
    then:
      priority: 4
      reason: EC_MATCH_CC_CAR

```

(these are a couple of AI-generated mock-ups of what these config files could look like - it would need more thought to ensure flexibility and robustness)

And then write a Python function to parse this and actually evaluate a resource's priority level based on the output. 

Then extend front-end to facilitate loading, building and saving of these config files. It would be able to access the list of patient and resource attributes as drop-downs, helping to ensure the proposed conditions are valid.
